[colors]

# Colores principales
[colors.primary]
background = "#101010"  # Negro oscuro pero no tan agresivo
foreground = "#C5C8C6"  # Azul claro estilo Tokyo Night

# Colores normales
[colors.normal]
black   = "#101010"
red     = "#f7768e"
green   = "#9ece6a"
yellow  = "#e0af68"
blue    = "#7aa2f7"
magenta = "#bb9af7"
cyan    = "#7dcfff"
white   = "#a9b1d6"

# Colores brillantes
[colors.bright]
black   = "#3b4261"  # Gris oscuro para comentarios, no tan fuerte
red     = "#f7768e"
green   = "#9ece6a"
yellow  = "#e0af68"
blue    = "#7aa2f7"
magenta = "#bb9af7"
cyan    = "#7dcfff"
white   = "#c0caf5"

